name = "wechat-notification"
type = "javascript"
workers_dev = true

[dev]
port = 9999
local_protocol = "http"

[build]
command = "webpack --config webpack/index.js"

[build.upload]
format = "service-worker"


[env.production]
workers_dev = false
webpack_config = "webpack.prod.js"
kv_namespaces = [
    { binding = "WECHAT_NOTICE_KV", id = "1ff9eb27795247408df742eaa13b2caa" }
]

[env.development]
workers_dev = true
webpack_config = "webpack.dev.js"
kv_namespaces = [
    { binding = "WECHAT_NOTICE_KV", preview_id = "1ff9eb27795247408df742eaa13b2caa",  id = "1ff9eb27795247408df742eaa13b2caa" }
]