name = "wechat-notification"
type = "javascript"
workers_dev = true
# account_id = 

[dev]
port = 9999
local_protocol = "http"

[build]
command = "webpack --config webpack/index.js"

[build.upload]
format = "service-worker"


[env.production]
workers_dev = true
# routes = [
#     "https://exmaple.com/*"
# ]
kv_namespaces = [
    { binding = "WECHAT_NOTICE_KV", id = "1ff9eb27795247408df742eaa13b2caa" }
]

[env.development]
workers_dev = true
kv_namespaces = [
    { binding = "WECHAT_NOTICE_KV", preview_id = "1ff9eb27795247408df742eaa13b2caa",  id = "1ff9eb27795247408df742eaa13b2caa" }
]